### ISSUE TITLE
Is this a hack?

### ISSUE THREAD

**Issue by Qiming-Liu** [DoooggyMarkCHAN/PUBGAssistant#1]

**Comment by DoooggyMarkCHAN** [comment]
technically, it is not a real hack, only a tool like other mouse macros

**Comment by Qiming-Liu** [comment]
Thanks for the amazing code and quick response! I'm also curious about your other repos, such as [AutoMeasuringWithOpenCV](https://github.com/DoooggyMarkCHAN/AutoMeasuringWithOpenCV). Will it lead to account ban during the coding and testing process?

**Comment by DoooggyMarkCHAN** [comment]
> Thanks for the amazing code and quick response! I'm also curious about your other repos, such as [AutoMeasuringWithOpenCV](https://github.com/DoooggyMarkCHAN/AutoMeasuringWithOpenCV). Will it lead to account ban during the coding and testing process?

No it will not trigger the ban, I have used it for more than 1 year.
